version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    branches:
      only:
        - master
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: |
            sudo docker-compose -f docker-compose.test.yml up -d
            sudo docker-compose exec django python manage.py test
            sudo docker-compose down
