version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    branches:
      only:
        - master
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: |
            ls
            sudo docker-compose -f docker-compose.test.yml up -d
            # sudo docker cp ./dockerTutorial django_container:/var/www/dockerTutorial
            # sudo docker exec -it django_container ls -al
            sudo docker-compose exec django ls -al
            # sudo docker-compose run django ls -al
            sudo docker-compose down
