version: 2
jobs:
  build:
    working_directory: /dockerTutorial
    docker:
      - image: docker:17.05.0-ce-git
    branches:
      only:
        - master
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            locate pip3
            apk add --update py-pip
            pip3 install --upgrade pip
            pip3 install docker-compose
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run django python manage.py test
