version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    branches:
      only:
        - master
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run tests
          command: |
            sudo docker-compose -f docker-compose.test.yml up -d --build
            sudo docker-compose run django test
            # sudo docker-compose run --entrypoint ls --rm django
