version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    branches:
      only:
        - master
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run tests
          command: |
            cat docker-compose.test.yml
            # sudo docker-compose up -d --build
            # sudo docker-compose run django test
